-- AlterTable
ALTER TABLE "ComputedElo" ALTER COLUMN "winCount" SET DEFAULT 0,
ALTER COLUMN "lossCount" SET DEFAULT 0,
ALTER COLUMN "lastMatch" SET DEFAULT '1970-01-01 00:00:00 +00:00';

-- AlterTable
ALTER TABLE "EloVersion" ADD COLUMN     "startingValue" DOUBLE PRECISION NOT NULL DEFAULT 1200;
